# 세미콜론 꼭 붙이기
server {
  listen 80;

  # Reverse Proxy
  # 클라이언트와 서버 사에이 위치하여 클라이언트 <-> 서버를 중계
  location /api/ {
    proxy_pass http://tasks-service.default:8000/; # tasks-service cluster-ip 주소의 도메인, http 요청은 기본 80 포트라 80 포트가 아니라면 명시해야 함
    # proxy_pass http://10.111.162.40:8000/ # cluster-ip 주소 자체로도 가능하나 주소 보안의 의미가 없어짐
    # proxy_pass http://127.0.0.1:45723/ # 로컬에서 브라우저 연결하는 주소로는 불가능
  }
  
  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri $uri/ /index.html =404;
  }
  
  include /etc/nginx/extra-conf.d/*.conf;
}