apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users # deployment에서 app label이 users인 경우만 적용
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
