apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  type: ClusterIP # 내부에서만 통신해도 되는 pod
  ports:
    - protocol: TCP
      port: 27017 # 서비스를 노출할 포트
      targetPort: 27017 # mongoDB 기본 포트
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: max
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: secret
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
